### ISSUE TITLE
Notifications break error tracking and throw errors on users without rights

### ISSUE THREAD

**Issue by davidsneighbour** [davidsneighbour/booka-issues#119]
1. When the browser stays open overnight then the notification script calls for updates ever x minutes, hereby creating thousands of silenced errors per day that get elevated to sentry.io
2. When the owner connects multiple BooKa instances to one Dropbox-App and/or folder then loading the open file requests breaks the system (no booking with the ID/Name available) and throws a tantrum

For now, I disabled cronjob on hdtravels and let it run on hdtours. 

### todo

- [ ] fix cronjob task
    - [ ] bow out graceful if a file request is encountered that can not be connected to a local booking
    - [ ] notify about errors
    - [ ] remove closed file requests and remove them from DB/system
- [ ] re-enable notifications after x seconds
- [ ] make notifications enable/disable via setup
- [ ] track user activity and prolong interval the notificationcheck is running
